export const CATEGORY = [
  "Antiquty",
  "Books",
  "Ceramics",
  "Chemical Alterations",
  "Digital Art",
  "Drawing",
  "Installation",
  "Paint!ng",
  "Painting",
  "Photography",
  "Print Making",
  "Relief Sculpture",
  "Sculpture",
  "Video",
];

export const ARTISTS = [
  "A Rajeshwara Rao",
  "A. Krishna Reddy",
  "AKBAR PADAMSEE",
  "AMIT AMBALAL",
  "ANJOLIE ELA MENON",
  "ANUPAM SUD",
  "APSARA",
  "ARPANA CAUR",
  "ARPITA SINGH",
  "ASHOK BHOWMICK",
  "Aaditi Joshi",
  "Aalap Shah",
  "Aaron Glasson",
  "Abani Sen",
  "Abdul Aziz Raiba",
  "Abdulrahiman Appabhai Almelkar",
  "Abdur Rahman Chughtai",
  "Abir Karmakar",
  "Achuthan Kudallur",
  "Adeela Suleman",
  "Adi M. Davierwalla",
  "Adimoolam, K.M.",
  "Aditi Singh",
  "Aditya Pande",
  "Ahmed Parvez",
  "Ahsan Jamal",
  "Aisha Rahim",
  "Ajay De",
  "Ajay Desai",
  "Ajay Dhandre",
  "Aji V.N.",
  "Ajit Chauhan",
  "Ajit Gupta",
  "Akhilesh ",
  "Albert Camus",
  "Alexis Kersey",
  "Ali Azmat",
  "Ali Kazim",
  "Alok Bal",
  "Alphonso Doss",
  "Alyssa Pheobus Mumtaz",
  "Amar Nath Sehgal",
  "Amarnath Sharma",
  "Amina Ahmed",
  "Amjad Ali Talpur",
  "Ananda Kentish Coomaraswamy",
  "Anant Joshi",
  "AndrÃƒÆ’Ã‚Â© Hambourg",
  "AndrÃƒÆ’Ã‚Â© Lanskoy",
  "Andy Warhol",
  "Aniket Khupse",
  "Anila Quayyum Agha",
  "Anindita Bhattacharya",
  "Anish Kapoor",
  "Anjana Mehra",
  "Anmana Devi",
  "Anoli Perera",
  "Antonio E. Costa",
  "Anup Mathew Thomas",
  "Anwar Jalal Shemza",
  "Apurba Nandi",
  "Aqui Thami",
  "Arshi Irshad Ahmadzai",
  "Arun KS",
  "Arunkumar H G",
  "Ashim Purkayashta",
  "Ashutosh Bhardwaj",
  "Asif Ahmed",
  "Asim Waqif",
  "Asit Kumar Haldar",
  "Asit Kumar Patnaik",
  "Attiya Shaukat",
  "Attributed to H A Gade",
  "Attributed to Manchershaw F Pithawalla",
  "Attributed to Sorab M Pithawalla",
  "Atul Bhalla",
  "Avinash Chandra",
  "Avishek Sen",
  "Ayaz Jokhio",
  "Ayesha Durrani",
  "B Manjunath Kamath",
  "BADRI NARAYAN",
  "BAIJU PARTHAN",
  "BHUPEN KHAKHAR",
  "BIKASH BHATTACHARJEE",
  "BIMAL DASGUPTA",
  "BINODE BEHARI MUKHERJEE",
  "BISWANATH MUKERJI",
  "BOSE KRISHNAMACHARI",
  "Babu Eshwar Prasad",
  "Babu Xavier",
  "Baburao Painter",
  "Bal Chhabda",
  "Balaji Ponna",
  "Balasubramaniam, A.",
  "Bani Abidi",
  "Barun Chowdhury",
  "Baua Devi",
  "Benitha Perciyal",
  "Bernard Buffet",
  "Bhagat, Dhanraj",
  "Bhairavi Modi",
  "Bhajju Shyam",
  "Bhanu Shah",
  "Bharat Sikka",
  "Bharti Kher",
  "Bhuvanesh Gowda",
  "Bijon Choudhury",
  "Bijoy Jain",
  "Bimala Dutt",
  "Binu Bhaskar",
  "Biplab Biswas",
  "Biren de 73",
  "Birendra Pani",
  "Buwa Shete",
  "C Bhagyanath",
  "C R Nanaiah",
  "C RAJA RAJA VARMA & Raja Ravi Varma",
  "C.S.N. Patnaik",
  "CHANDRA BHATTACHARJEE",
  "CHITTAPROSAD BHATTACHARYA",
  "CHITTROVANU MAZUMDAR",
  "Camille Pissarro",
  "Chameli Ramachandran",
  "Charles Camoin",
  "Charles Crombie",
  "Chaudhuri, Sankho",
  "Chen Ke",
  "Chintamoni Kar",
  "Chintan Upadhyay",
  "Chirodeep Chaudhuri",
  "Chitra Ganesh",
  "Chowdhury, Arunanshu",
  "D L N Reddy",
  "DATTA BANSODE",
  "DHARAMANARAYAN DASGUPTA",
  "Daan Botlek",
  "Daku ",
  "Das, Amitava",
  "Das, Arup",
  "Das, Haren",
  "Das, Sailbal",
  "Das, Samit",
  "Das, Sunil",
  "David Hockney",
  "Dayanita Singh",
  "Debanjan Roy",
  "Debasish Mukherjee",
  "Debraj Goswami",
  "Deepak Sonar",
  "Deepak Tandon",
  "Delphin Enjolras",
  "Desmond Lazaro",
  "Devraj Dakoji",
  "Dhananjay Singh",
  "Dhruva Mistry",
  "Dhruvi Acharya",
  "Dileep Sharma",
  "Dilip Chobisa",
  "Dilip Ranade",
  "Dinesh Khanna",
  "Dodiya, Anju",
  "Dodiya, Atul",
  "Double-sided page from a Bhagwat Purana",
  "Douglas, C.",
  "Dube, Anita",
  "Dulare Devi",
  "Dwarapala ",
  "Early Bengal School",
  "Ebenezer Sunder Singh",
  "Edouard Vuillard",
  "Edric Wirth",
  "Edward Seago",
  "Edwin Lord Weeks",
  "Edwin Mullins",
  "Faiza Butt",
  "Farhad Hussain",
  "Farida Batool",
  "Ferdinand du Puigaudeau",
  "Fernand LÃƒÆ’Ã‚Â©ger",
  "Francesco Clemente",
  "Francis Bacon",
  "Francis Newton Souza",
  "G. Ravinder Reddy",
  "GANESH HALOI",
  "GANESH PYNE",
  "GEORGE KEYT",
  "GOGI SAROJ PAL",
  "GOPAL GHOSE",
  "GULAM MOHAMMED SHEIKH",
  "GURCHARAN SINGH",
  "Gaganendranath Tagore",
  "Ganesha",
  "Ganga",
  "Gargi Raina",
  "Gauri",
  "Gauri Gill",
  "Ge Guanzhong",
  "George Martin",
  "Georges Braque",
  "Georges dÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢Espagnat",
  "Georgia Hill",
  "Gieve Patel",
  "Gigi Scaria",
  "Girish Dahiwale",
  "Girjesh Kumar Singh",
  "Goddess Sridevi",
  "Gopal Saha",
  "Gopikrishna ",
  "Govind Madhav Solegaonkar",
  "Guillermo Rubi",
  "Gulam Rasool Santosh",
  "Gupta, Subodh",
  "Gupta, Sunil",
  "Gurusiddappa G E",
  "Gustave Loiseau",
  "HEMENDRANATH MAJUMDAR",
  "Haldankar, A.L.",
  "Hari Ambadas Gade",
  "Harsha, N.S.",
  "Hasnat Mehmood",
  "Head of Buddha ",
  "Heeral Trivedi",
  "Hema Upadhyay",
  "Henri Lebasque",
  "Henri Manguin",
  "Henri Matisse",
  "Henry Moore",
  "Hira Devi",
  "Horace Van Ruith",
  "Howard Hodgkin",
  "Huma Mulji",
  "Ian Lancaster Fleming",
  "Ida Kar",
  "Idris Khan",
  "Ila Pal",
  "Imran Mudassar",
  "Imran Qureshi",
  "Iranna, G.R.",
  "Iranna, Pooja",
  "J. Sultan Ali",
  "JAGDISH SWAMINATHAN",
  "JALANDARNATH",
  "JAYASRI BURMAN",
  "JEHANGIR JANI",
  "JEHANGIR SABAVALA",
  "JITISH KALLAT",
  "JOGEN CHOWDHURY",
  "Jacques Lassaigne",
  "Jagannath Mohapatra",
  "Jagannath Panda",
  "Jai Zharotia",
  "Jaidev Baghel",
  "Jaishri Abichandani",
  "James Vere Stewart Wilkinson and Sir Thomas Walker Arnold",
  "Jamil Naqsh",
  "Jamini Roy",
  "Jangarh Singh Shyam",
  "Japani Shyam",
  "Jayashree Chakravarty",
  "Jean Cocteau",
  "Jean-Baptiste- Armand Guillaumin",
  "Jeram Patel",
  "Jitu Oghani",
  "Jivya Soma Mashe",
  "Joan MirÃƒÆ’Ã‚Â³",
  "Joel Arthur Rosenthal and Pierre Jeannet",
  "John Maynard Keynes",
  "John le CarrÃƒÆ’Ã‚Â© ",
  "Justin Ponmany",
  "Jyothi Basu",
  "Jyoti Bhatt",
  "K M Madhusudhanan",
  "K Reghunadhan",
  "K S Radhakrishnan",
  "K S Ranjitsinhji",
  "K. C. S. Paniker",
  "K. G. Subramanyan",
  "K. Laxma Goud",
  "K. S. Kulkarni",
  "KARTICK PYNE",
  "KRISHEN KHANNA",
  "KRISHNA YEARNING FOR HIS LOVER",
  "Kalighat Pat",
  "Kanishka Ingle",
  "Karl Antao",
  "Karl Khandalavala",
  "Kartik Sood",
  "Kattingeri Krishna Hebbar",
  "Ketaki Sheth",
  "Khadim Ali",
  "Kirann Telkar",
  "Kishor Shinde",
  "Kishore Chakraborthy",
  "Krishna Hawlaji Ara",
  "Krishnaraj Chonat",
  "Kriti Arora",
  "Kumar, Bari",
  "LALU PRASAD SHAW",
  "LORD BRAHMA IN STANDING POSTURE",
  "LORD GANESHA SEATED",
  "Lado Bai",
  "Lakshmi Gademane",
  "Lancelot Ribeiro",
  "Laurence and Patrick Seguin",
  "Laxman Pai",
  "Laxman Shreshtha",
  "Lord Buddha with Arch",
  "Louis Valtat",
  "Ludwig Bachhofer",
  "Lynn Chadwick",
  "M S Joshi",
  "M Sivanesan",
  "M. Reddeppa Naidu",
  "MALE BUST",
  "MANISHA GERA BASWANI",
  "MANJIT BAWA",
  "Madhav Satwalekar",
  "Madhavrao Krishnarao Parandekar",
  "Madhvi Subrahmanian",
  "Mahadev Visvanath Dhurandhar",
  "Mahendra Sinh",
  "Mahreen Zuberi",
  "Manchershaw F Pithawalla",
  "Manish Modi",
  "Manish Nai",
  "Manish Pushkale",
  "Manoj Dutta",
  "Mansoor Ali",
  "Maqbool Fida Husain",
  "Marc Chagall",
  "Marino Marini",
  "Martand Khosla",
  "Maurice Brianchon",
  "Maurice de Vlaminck",
  "Maximilien Luce",
  "Meera Devidayal",
  "Miao Xiaochun",
  "Michael Silas",
  "Minal Damani",
  "Moeen Faruki",
  "Mohammad Ali Talpur",
  "Mohammad Shakil Saigol",
  "Mohan Samant",
  "Monali Meher",
  "Mookherjea, Sailoz",
  "Muhammad Atif Khan",
  "Muhammad Zeeshan",
  "Mukherjee, Meera",
  "Mukherjee, Mrinalini",
  "Mulk Raj Anand",
  "Multiple Artists",
  "N R Sardesai",
  "NALINI MALANI",
  "NATARAJ SHARMA",
  "NEERAJ GOSWAMI",
  "NIKHILESWAR BARUAH",
  "NOBLEMAN",
  "NONE",
  "Naeem Rana",
  "Nagji Patel",
  "Naiza Khan",
  "Nandalal Bose",
  "Nandan Ghiya",
  "Nandini Valli Muthiah",
  "Narayan Shridhar Bendre",
  "Nasreen Mohamedi",
  "Natessa Amin",
  "Natvar Bhavsar",
  "Navjot ",
  "Nicholas Roerich",
  "Nicholas Roerich, Vsevolod Ivanov and Erikh Fedorovich Gollerbakh",
  "Nicola Durvasula",
  "Nidhi Agarwal",
  "Nikhil Chopra",
  "Nilima Sheikh and Gulam Mohammed Sheikh",
  "Nityam Singha Ray",
  "Nusra Latif Qureshi",
  "OWAIS HUSAIN",
  "Olivia Fraser",
  "Om Prakash Sharma",
  "Ompal Sansanwal",
  "P S Jalaja",
  "P T Reddy",
  "P. V. Janakiram",
  "PARAMJIT SINGH",
  "PARESH MAITY",
  "PARITOSH SEN",
  "PRABHAKAR BARWE",
  "PRABHAKAR M KOLTE",
  "PRAKASH KARMARKAR",
  "PRASANTA SAHU",
  "Pablo Picasso",
  "Pablo Picasso and Georges Boudaille",
  "Pala Pothupitiye",
  "Pandit Khairnar",
  "Parag Sonarghare",
  "Parekh, Madhvi",
  "Parekh, Manisha",
  "Parekh, Manu",
  "Parul Gupta",
  "Parul Thacker",
  "Parvathi Nayar",
  "Peng Wei",
  "Phaneendra Nath Chaturvedi",
  "Pierre-Eugene Montezin",
  "Pilloo Pochkhanawala",
  "Piraji Sagara",
  "Piyali Ghosh",
  "Piyali Sadhukhan",
  "Prabha, B.",
  "Prabir C. Purkayastha",
  "Prabuddha Dasgupta",
  "Pradeep Mishra",
  "Prajakta Palav Aher",
  "Prajakta Potnis",
  "Prajjwal Chowdhury",
  "Pramod Gopalkrishnan",
  "Praneet Soi",
  "Prantik Chattopadhyay",
  "Prashant Panjiar",
  "Pratap Morey",
  "Pratul Dash",
  "Prithpal Singh Ladi",
  "Probir Gupta",
  "Prodosh Das Gupta",
  "Pushpamala N and Clare Arni",
  "Pushpamala, N.",
  "Putli Ganju",
  "R M Palaniappan",
  "RABIN MONDAL",
  "RAJENDRA DHAWAN",
  "RAM KUMAR",
  "RAMANANDA BANDYOPADHYAY",
  "RAMESHWAR BROOTA",
  "RAMKINKAR BAIJ",
  "RAQS Media Collective ",
  "REKHA RODWITTIYA",
  "Rabindranath Tagore",
  "Rabindranath Tagore and Sakti Burman",
  "Radha Charan Bagchi",
  "Raghu Rai",
  "Raghubir Singh",
  "Rahul Vajale",
  "Raj Kumar",
  "RajGuru AP",
  "Raja Ravi Varma",
  "Rajan Krishnan",
  "Rajendra Kumar Shyam",
  "Rajendran, Sumedh",
  "Rajesh P.S.",
  "Rajesh Pullarwar",
  "Rajesh Ram",
  "Rajib Chowdhury",
  "Rajkumar Paswan",
  "Rajnish Kaur",
  "Ram Bali Chauhan",
  "Ram Rahman",
  "Ram Singh Urveti",
  "Rama Varma",
  "Ramachandran, A.",
  "Ramanujam, K.G.",
  "Ramgopal Vijaivargiya",
  "Rana Begum",
  "Ranbir Singh Kaleka",
  "Raoul Dufy",
  "Raqib Shaw",
  "Rashid Rana",
  "Ratheesh T",
  "Rathin Barman",
  "Ravi Shah",
  "Ravikumar Kashi",
  "Ray, Anandajit",
  "Reba Hore",
  "Reena Saini Kallat",
  "Rehana Mangi",
  "Reji Arackal",
  "Reji, K.P.",
  "Remen Chopra",
  "Richard Bartholomew and Shiv S Kapur",
  "Rimzon, N.N.",
  "Rina Banerjee",
  "Rithika Pandey",
  "Riyas Komu",
  "Robert Montgomery",
  "Rohini Devasher",
  "Ronak Sopariwala",
  "Roy Lichtenstein",
  "Roy Thomas",
  "S Dhanapal",
  "S H Raza & Akbar Padamsee",
  "S HARSHAVARDHANA",
  "S Nandagopal",
  "S. Paul",
  "SAKTI BURMAN",
  "SANJAY BHATTACHARYA",
  "SATISH GUJRAL",
  "SHIAVAX CHAVDA",
  "SHIBU NATESAN",
  "SHIVA",
  "SHYAMAL DUTTA RAY",
  "SOMNATH HOREÃƒÂ¯Ã‚Â¿Ã‚Â½",
  "SUDHIR PATWARDHAN",
  "SUJATA BAJAJ",
  "SUNIL GAWDE",
  "SUNIL PADWAL",
  "SURENDRAN NAIR",
  "Sachin Karne",
  "Sadanand K. Bakre",
  "Sadanand Shirke",
  "Sadashiv Mashe",
  "Sadequain",
  "Sadhna Prasad",
  "Sahej Rahal",
  "Saira Wasim",
  "Sajid Wajid Shaikh",
  "Saju Kunhan",
  "Sakshi Gupta",
  "Salvador Dali",
  "Samanta Batra Mehta",
  "Samaraendra Raj Singh",
  "Sameer Kulavoor",
  "Sanam C Narayanan",
  "Sangeeta Gupta",
  "Sanjay Kumar Singh",
  "Sanjeev Sonpimpare",
  "Santana Gohain",
  "Sanyal, B.C.",
  "Saradacharan Ukil",
  "Sarbari Roy Chowdhury",
  "Sarika Mehta",
  "Satadru Sovan Banduri",
  "Sayed Haider Raza",
  "Schandra Singh",
  "School of Raja Ravi Varma",
  "Seated Ayyanar",
  "Seated Ganesha ",
  "Seher Shah",
  "Sen, Mithu",
  "Senaka Senanayake",
  "Shah, Haku",
  "Shah, Himmat",
  "Shahid Datawala",
  "Shahzia Sikander",
  "Shan Bhatnagar",
  "Shankar Balwant Palsikar",
  "Shanti Dave",
  "Sheba Chhachhi",
  "Sheetal Gattani",
  "Sheikh, Nilima",
  "Sheila Makhijani",
  "Sher-Gil, Amrita",
  "Shezad Dawood",
  "Shifali N Mehra",
  "Shilpta Gupta",
  "Shoaib Mehmood",
  "Shobha Broota",
  "Shreyasi Chatterjee",
  "Siji Krishnan",
  "Simryn Gill",
  "Singh, Anjum",
  "Sir Jacob Epstein",
  "Smriti Dixit",
  "Sohan Qadri",
  "Sojwal Samant",
  "Soorya, O.",
  "Sorab M Pithawalla",
  "Sosa Joseph",
  "Standing Devi",
  "Standing Vishnu",
  "Standing Vishnu with Prabha",
  "Subba Ghosh",
  "Sudarshan Shetty",
  "Sudhanshu Choudhary",
  "Sudhanshu Sutar",
  "Sudhir Bhagat",
  "Sudhir Ranjan Khastgir",
  "Sudip Roy",
  "Suhasini Kejriwal",
  "Sujith SN",
  "Sumaira Tazeen",
  "Sumesh Balakrishnan",
  "Suneel Mamadapur",
  "Sunil K",
  "Surekha ",
  "T M Azis",
  "T S Satyan",
  "T. V. Santhosh",
  "T. Venkanna",
  "THOTA VAIKUNTAM",
  "TORSO",
  "TYEB MEHTA",
  "Talha Rathore",
  "Tallur L N",
  "Tanujaa Rane",
  "Tanya Goel",
  "Tapas Sarkar",
  "Tayeba Begum Lipi",
  "Tazeen Qayyum",
  "Tehmuras Constable",
  "Tejal Shah",
  "Tellas ",
  "The Ravi Varma Press",
  "Thomas Daniell",
  "Thomas Hickey",
  "Thomas Holbein Hendley",
  "Thukral and Tagra",
  "Tirthankara Mahavir",
  "Toofan Rafai",
  "Tushar Joag",
  "Uma-Maheshwara",
  "Unknown Photographer",
  "Ustad Allah Bux",
  "Utkarsh Makwana",
  "V M Sholapurkar",
  "V Ramesh",
  "V S Naipaul",
  "VASUNDHARA TEWARI",
  "VISWANADHAN VELU",
  "Vaishali Raut",
  "Valay Shende",
  "Valsan Koorma Kolleri",
  "Varunika Saraf",
  "Vasudeo Pandya",
  "Vasudeo S. Gaitonde",
  "Vasudev, S.G.",
  "Vasudevan Akkitham",
  "Vasudha Thozhur",
  "Vayeda Brothers",
  "Ved Prakash Gupta",
  "Vidura Jang Bahadur",
  "Vincent van Gogh",
  "Vineet Kacker",
  "Vipul Prajapati",
  "Viraj Naik",
  "Vishwanath Nageshkar",
  "Vithal, B.",
  "Vivan Sundaram",
  "Vivek Vilasini",
  "WOODEN PANEL",
  "Walter Langhammer",
  "Waqas Khan",
  "Waseem Ahmed",
  "Waswo X Waswo",
  "William Daniell",
  "Wooden Panel",
  "Wu Yi",
  "Xu Lei",
  "YUSUF ARAKKAL",
  "Yamini Nayar",
  "Yashika Sugandh",
  "Yashwant Deshmukh",
  "Yoh Nagao",
  "Yok & Sheryo",
  "Youdhisthir Maharjan",
  "Zahoor ul Akhlaq",
  "Zakkir Hussain",
  "Zarina Hashmi",
];
